name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest optuna xgboost pandas scikit-learn numpy matplotlib seaborn

    - name: Run unit tests for data_engineering and Model
      run: |
        # Exécuter les tests dans les dossiers data_engineering et Model
        python -m unittest discover -s test/data_engineering
        python -m unittest discover -s test/Model

    - name: Run pylint on src/
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pylint src || true  # Exécution de pylint sur tout le dossier src/

    - name: Upload test results to GitHub Actions (optional)
      if: success()  
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results  
