name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest optuna xgboost pandas scikit-learn numpy matplotlib seaborn

    - name: Run unit tests for data_engineering and Model
      run: |
        python -m unittest discover -s test/data_engineering -p "test_*.py"
        python -m unittest discover -s test/Model -p "test_*.py"

    - name: Run pylint on src/
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pylint src || true  # Exécution de pylint sur tout le dossier src/
